# Generated by Django 5.2.5 on 2025-11-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='medio_pago',
            field=models.CharField(default='Efectivo', max_length=50),
        ),
    ]
